<#
AIIO Case Workspace V3 preview
Persistent Case -> Step -> Artifact model plus trusted work-order intake.
Loaded after AIIO v2 services; legacy sessions remain available underneath.
#>

$Script:PMMAIIOCaseSchema='PMM_AIIO_CASE_V3_PREVIEW1'
$Script:PMMAIIOWorkOrderSchema='PMM_AIIO_WORK_ORDER_V1'
$Script:PMMAIIOCaseProgressCallback=$null
$Script:PMMAIIOCaseCancelRequested=$false

function Get-PMMAIIOCaseRoot {
  $root=Join-PMMPath 'AIIO' 'Cases'
  if(-not(Test-Path -LiteralPath $root -PathType Container)){New-Item -ItemType Directory -Force -Path $root|Out-Null}
  return $root
}
function Test-PMMAIIOCaseId([string]$Id){return (-not[string]::IsNullOrWhiteSpace($Id) -and $Id -cmatch '^AICASE-[0-9]{8}-[0-9]{6}-[a-f0-9]{8}$')}
function New-PMMAIIOCaseId{return ('AICASE-'+[DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,8))}
function Get-PMMAIIOCasePath([string]$Id){if(-not(Test-PMMAIIOCaseId $Id)){throw 'Invalid AIIO case ID.'};return (Join-Path (Get-PMMAIIOCaseRoot) $Id)}
function Get-PMMAIIOCaseStepsPath([string]$Id){return (Join-Path (Get-PMMAIIOCasePath $Id) 'steps')}
function Get-PMMAIIOCaseEvidencePath([string]$Id){return (Join-Path (Get-PMMAIIOCasePath $Id) 'evidence')}
function Get-PMMAIIOCaseHandoffsPath([string]$Id){return (Join-Path (Get-PMMAIIOCasePath $Id) 'handoffs')}
function Initialize-PMMAIIOCaseFolder([string]$Id){$root=Get-PMMAIIOCasePath $Id;foreach($n in @('steps','evidence','handoffs','inbox','imports','artifacts')){$p=Join-Path $root $n;if(-not(Test-Path -LiteralPath $p -PathType Container)){New-Item -ItemType Directory -Force -Path $p|Out-Null}};return $root}

function Write-PMMAIIOCaseJson([string]$Path,$Value,[int]$Depth=70){
  if(Get-Command Write-PMMAIIOJsonAtomic -ErrorAction SilentlyContinue){Write-PMMAIIOJsonAtomic $Path $Value $Depth;return}
  $parent=Split-Path -Parent $Path;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};$Value|ConvertTo-Json -Depth $Depth|Set-Content -LiteralPath $Path -Encoding UTF8
}
function Copy-PMMAIIOCaseObject($Value,[int]$Depth=70){if($null -eq $Value){return $null};return ($Value|ConvertTo-Json -Depth $Depth|ConvertFrom-Json)}
function Normalize-PMMAIIOCaseType([string]$Type){$v=([string]$Type).Trim().ToUpperInvariant().Replace('-','_').Replace(' ','_');switch($v){'CREATE_MOD'{'NEW_MOD'};'NEW_MOD'{'NEW_MOD'};'FIX'{'FIX_MOD'};'FIX_MOD'{'FIX_MOD'};'MODIFY_MOD'{'FIX_MOD'};'COMPAT'{'COMPATIBILITY'};'COMPATIBILITY'{'COMPATIBILITY'};'UNSUPPORTED_CONFLICT'{'COMPATIBILITY'};default{'UNDEFINED'}}}
function Normalize-PMMAIIOCaseTransport([string]$Transport){$v=([string]$Transport).Trim().ToUpperInvariant().Replace('-','_').Replace(' ','_');switch($v){'MANUAL'{'MANUAL_ZIP'};'MANUAL_ZIP'{'MANUAL_ZIP'};'AGENT'{'AGENT_SERVER'};'AGENT_SERVER'{'AGENT_SERVER'};'GITHUB'{'GIT'};'GIT'{'GIT'};'NEXUS'{'NEXUS'};'URL'{'LINK'};'LINK'{'LINK'};default{'AUTO'}}}
function Get-PMMAIIOCaseTypeLabel([string]$Type){switch(Normalize-PMMAIIOCaseType $Type){'NEW_MOD'{'New Mod'};'FIX_MOD'{'Fix Mod'};'COMPATIBILITY'{'Compatibility'};default{'Undefined / Research'}}}
function Get-PMMAIIOCaseNextLabel([string]$Action){switch(([string]$Action).ToUpperInvariant()){'CREATE_HANDOFF'{'Create handoff'};'PROCESS_REQUESTS'{'Process requested work'};'WAIT_FOR_AI'{'Receive from AI'};'REVIEW_CANDIDATE'{'Review candidate'};'USER_DECISION'{'User decision'};'EDIT_OR_CREATE_HANDOFF'{'Edit case / create handoff'};default{'Current'}}}

function Save-PMMAIIOCase($Case){
  if(-not$Case -or -not(Test-PMMAIIOCaseId ([string]$Case.CaseId))){throw 'Invalid AIIO case.'}
  $Case.UpdatedUtc=[DateTime]::UtcNow.ToString('o');Initialize-PMMAIIOCaseFolder ([string]$Case.CaseId)|Out-Null
  Write-PMMAIIOCaseJson (Join-Path (Get-PMMAIIOCasePath ([string]$Case.CaseId)) 'case.json') $Case 80;return $Case
}
function Get-PMMAIIOCase([string]$Id){
  if(-not(Test-PMMAIIOCaseId $Id)){return $null};$p=Join-Path (Get-PMMAIIOCasePath $Id) 'case.json';if(-not(Test-Path -LiteralPath $p -PathType Leaf)){return $null}
  try{$c=Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$c.Schema -eq $Script:PMMAIIOCaseSchema){return $c}}catch{};return $null
}
function Get-PMMAIIOCases{
  $rows=[Collections.Generic.List[object]]::new();foreach($d in @(Get-ChildItem -LiteralPath (Get-PMMAIIOCaseRoot) -Directory -ErrorAction SilentlyContinue)){$c=Get-PMMAIIOCase $d.Name;if($c){$rows.Add($c)}}
  return @($rows.ToArray()|Sort-Object @{Expression={try{[DateTimeOffset]$_.UpdatedUtc}catch{[DateTimeOffset]::MinValue}};Descending=$true})
}
function New-PMMAIIOCase{
  param([string]$Title='New AIIO case',[string]$Type='UNDEFINED',[string]$Description='',[string]$Transport='AUTO',[string]$CaseId='',[string]$LegacySessionId='',[string]$WorkOrderId='',[switch]$NoInitialStep)
  $id=if(Test-PMMAIIOCaseId $CaseId){$CaseId}else{New-PMMAIIOCaseId};$now=[DateTime]::UtcNow.ToString('o');Initialize-PMMAIIOCaseFolder $id|Out-Null
  $c=[pscustomobject][ordered]@{Schema=$Script:PMMAIIOCaseSchema;CaseId=$id;Title=$(if($Title){$Title}else{'New AIIO case'});Type=(Normalize-PMMAIIOCaseType $Type);Description=[string]$Description;Transport=(Normalize-PMMAIIOCaseTransport $Transport);Status='DRAFT';CreatedUtc=$now;UpdatedUtc=$now;CurrentStep=0;SelectedStep=0;LastAction='Case created';NextAction='EDIT_OR_CREATE_HANDOFF';TrustedInbound=$false;LegacySessionId=$LegacySessionId;WorkOrderId=$WorkOrderId;References=[pscustomobject]@{Mods=@();VanillaFamilies=@();Artifacts=@()};PendingActions=@();CompletedActions=@();FailedActions=@();LatestInbound='';LatestHandoff='';ActiveOperation=[pscustomobject]@{Running=$false;Message='';Current=0;Total=100;Indeterminate=$false;CompletedUtc=''}}
  Save-PMMAIIOCase $c|Out-Null;if(-not$NoInitialStep){Add-PMMAIIOCaseStep $c 'CASE_CREATED' ('Created '+(Get-PMMAIIOCaseTypeLabel $c.Type)+' case') 'EDIT_OR_CREATE_HANDOFF' @() $null|Out-Null};return (Get-PMMAIIOCase $id)
}
function Remove-PMMAIIOCase([string]$Id){$c=Get-PMMAIIOCase $Id;if(-not$c){return};if($c.LegacySessionId -and (Get-Command Set-PMMAIIOSessionArchived -ErrorAction SilentlyContinue)){try{Set-PMMAIIOSessionArchived -SessionId ([string]$c.LegacySessionId) -Archived $true|Out-Null}catch{}};Remove-Item -LiteralPath (Get-PMMAIIOCasePath $Id) -Recurse -Force}

function Get-PMMAIIOCaseSnapshot($Case){return [pscustomobject]@{Title=[string]$Case.Title;Type=[string]$Case.Type;Description=[string]$Case.Description;Transport=[string]$Case.Transport;Status=[string]$Case.Status;LastAction=[string]$Case.LastAction;NextAction=[string]$Case.NextAction;TrustedInbound=[bool]$Case.TrustedInbound;References=(Copy-PMMAIIOCaseObject $Case.References);PendingActions=(Copy-PMMAIIOCaseObject $Case.PendingActions);CompletedActions=(Copy-PMMAIIOCaseObject $Case.CompletedActions);FailedActions=(Copy-PMMAIIOCaseObject $Case.FailedActions)}}
function Add-PMMAIIOCaseStep($Case,[string]$Kind,[string]$Summary,[string]$NextAction,[array]$Artifacts,$Details){
  $Case.CurrentStep=[int]$Case.CurrentStep+1;$Case.SelectedStep=[int]$Case.CurrentStep;$Case.LastAction=$Summary;if($NextAction){$Case.NextAction=$NextAction};$Case.Status=$(if($Case.NextAction -eq 'CREATE_HANDOFF'){'READY_FOR_HANDOFF'}elseif($Case.NextAction -eq 'WAIT_FOR_AI'){'WAITING_FOR_AI'}else{[string]$Case.Status});Save-PMMAIIOCase $Case|Out-Null
  $s=[pscustomobject][ordered]@{Schema='PMM_AIIO_CASE_STEP_V1';CaseId=[string]$Case.CaseId;StepNumber=[int]$Case.CurrentStep;Utc=[DateTime]::UtcNow.ToString('o');Kind=$Kind;Summary=$Summary;NextAction=[string]$Case.NextAction;Artifacts=@($Artifacts);Details=$Details;State=(Get-PMMAIIOCaseSnapshot $Case)}
  Write-PMMAIIOCaseJson (Join-Path (Get-PMMAIIOCaseStepsPath ([string]$Case.CaseId)) ('step-{0:D4}.json' -f [int]$s.StepNumber)) $s 90;return $s
}
function Get-PMMAIIOCaseStep([string]$Id,[int]$N){if($N -lt 1){return $null};$p=Join-Path (Get-PMMAIIOCaseStepsPath $Id) ('step-{0:D4}.json' -f $N);if(-not(Test-Path -LiteralPath $p)){return $null};try{return (Get-Content -LiteralPath $p -Raw -Encoding UTF8|ConvertFrom-Json)}catch{return $null}}
function Get-PMMAIIOCaseSteps([string]$Id){$r=[Collections.Generic.List[object]]::new();foreach($f in @(Get-ChildItem -LiteralPath (Get-PMMAIIOCaseStepsPath $Id) -Filter 'step-*.json' -File -ErrorAction SilentlyContinue)){$s=Get-PMMAIIOCaseStep $Id ([int]([IO.Path]::GetFileNameWithoutExtension($f.Name).Substring(5)));if($s){$r.Add($s)}};return @($r.ToArray()|Sort-Object StepNumber -Descending)}
function Set-PMMAIIOCaseSelectedStep([string]$Id,[int]$N){$c=Get-PMMAIIOCase $Id;if(-not$c){throw 'Case not found.'};if($N -lt 1 -or $N -gt [int]$c.CurrentStep){throw 'Step outside history.'};$c.SelectedStep=$N;Save-PMMAIIOCase $c|Out-Null;return (Get-PMMAIIOCase $Id)}

function Set-PMMAIIOCaseProgress([string]$Id,[int]$Current,[int]$Total,[string]$Message,[switch]$Indeterminate,[switch]$Completed){$c=Get-PMMAIIOCase $Id;if($c){$c.ActiveOperation=[pscustomobject]@{Running=(-not[bool]$Completed);Message=$Message;Current=$Current;Total=$Total;Indeterminate=[bool]$Indeterminate;CompletedUtc=$(if($Completed){[DateTime]::UtcNow.ToString('o')}else{''})};Save-PMMAIIOCase $c|Out-Null};if($Script:PMMAIIOCaseProgressCallback){try{& $Script:PMMAIIOCaseProgressCallback $Id $Current $Total $Message ([bool]$Indeterminate) ([bool]$Completed)}catch{}}}
function Stop-PMMAIIOCaseAutomation{$Script:PMMAIIOCaseCancelRequested=$true}
function Reset-PMMAIIOCaseAutomation{$Script:PMMAIIOCaseCancelRequested=$false}

function Add-PMMAIIOCaseModReference([string]$Id,[string]$Path,[string]$Mode='FULL_PAK',[array]$Families=@()){
  $c=Get-PMMAIIOCase $Id;if(-not$c){throw 'Case not found.'};$full=[IO.Path]::GetFullPath($Path);if(-not(Test-Path -LiteralPath $full -PathType Leaf)){throw 'PAK not found.'};$ref=[pscustomobject]@{Kind='MOD';Name=[IO.Path]::GetFileName($full);Path=$full;Sha256=(Get-Sha256 $full);Mode=$Mode;Families=@($Families)};$c.References.Mods=@($c.References.Mods)+@($ref);Save-PMMAIIOCase $c|Out-Null;Add-PMMAIIOCaseStep $c 'REFERENCE_ADDED' ('Added mod reference: '+$ref.Name) ([string]$c.NextAction) @() $ref|Out-Null;return (Get-PMMAIIOCase $Id)
}
function Add-PMMAIIOCaseVanillaReference([string]$Id,[string]$LogicalPath){$c=Get-PMMAIIOCase $Id;if(-not$c){throw 'Case not found.'};$n=([string]$LogicalPath).Replace('\','/').Trim();if([IO.Path]::GetExtension($n) -ine '.uasset'){throw 'Vanilla family must be an exact .uasset logical path.'};$r=[pscustomobject]@{Kind='VANILLA_FAMILY';LogicalPath=$n;Mode='FAMILY'};$c.References.VanillaFamilies=@($c.References.VanillaFamilies)+@($r);Save-PMMAIIOCase $c|Out-Null;Add-PMMAIIOCaseStep $c 'REFERENCE_ADDED' ('Added Vanilla family: '+$n) ([string]$c.NextAction) @() $r|Out-Null;return (Get-PMMAIIOCase $Id)}
function Remove-PMMAIIOCaseReference([string]$Id,[string]$Bucket,[int]$Index){$c=Get-PMMAIIOCase $Id;if(-not$c){return};if($Bucket -eq 'Mods'){$a=@($c.References.Mods);if($Index -ge 0 -and $Index -lt $a.Count){$out=@();for($i=0;$i -lt $a.Count;$i++){if($i -ne $Index){$out+=,$a[$i]}};$c.References.Mods=$out}}elseif($Bucket -eq 'Vanilla'){$a=@($c.References.VanillaFamilies);if($Index -ge 0 -and $Index -lt $a.Count){$out=@();for($i=0;$i -lt $a.Count;$i++){if($i -ne $Index){$out+=,$a[$i]}};$c.References.VanillaFamilies=$out}};Save-PMMAIIOCase $c|Out-Null;return (Get-PMMAIIOCase $Id)}

function Initialize-PMMAIIOCasesFromLegacySessions{
  if(-not(Get-Command Get-PMMAIIOSessions -ErrorAction SilentlyContinue)){return};foreach($row in @(& $Script:PMMAIIOCaseOriginalGetSessions)){
    try{if([bool]$row.Archived){continue};$sid=[string]$row.SessionId;if(@(Get-PMMAIIOCases|Where-Object{[string]$_.LegacySessionId -eq $sid}).Count -gt 0){continue};$s=Get-PMMAIIOSession $sid;if(-not$s){continue};$c=New-PMMAIIOCase -Title ([string]$s.Title) -Type ([string]$s.TaskType) -Description ([string]$s.UserDescription) -Transport 'MANUAL_ZIP' -LegacySessionId $sid -NoInitialStep;$c.Status=[string]$s.Status;$c.NextAction=$(if([string]$s.Status -eq 'NeedsData'){'PROCESS_REQUESTS'}elseif([string]$s.Status -eq 'CandidateReady'){'REVIEW_CANDIDATE'}elseif([string]$s.Status -eq 'WaitingForAI'){'WAIT_FOR_AI'}else{'EDIT_OR_CREATE_HANDOFF'});Save-PMMAIIOCase $c|Out-Null;Add-PMMAIIOCaseStep $c 'LEGACY_IMPORTED' ('Imported existing AIIO exchange: '+[string]$s.Status) ([string]$c.NextAction) @() $null|Out-Null}catch{try{Write-PMMLog ('AIIO case migration warning: '+$_.Exception.Message)}catch{}}
  }
}

function Test-PMMAIIOCaseZipEntry([string]$Name){$n=$Name.Replace('\','/');if([string]::IsNullOrWhiteSpace($n) -or $n.StartsWith('/') -or $n -match '^[A-Za-z]:' -or $n -match '(^|/)\.\.(/|$)'){return $false};return $true}
function Read-PMMAIIOWorkOrder([string]$Path){
  if([IO.Path]::GetExtension($Path) -ieq '.json'){try{$d=Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$d.schema -eq $Script:PMMAIIOWorkOrderSchema){return $d}}catch{};return $null}
  if([IO.Path]::GetExtension($Path) -ine '.zip'){return $null};Add-Type -AssemblyName System.IO.Compression.FileSystem;$z=[IO.Compression.ZipFile]::OpenRead($Path);try{$e=@($z.Entries|Where-Object{([string]$_.FullName).Replace('\','/') -ceq 'workorder.json'});if($e.Count -ne 1){return $null};$r=[IO.StreamReader]::new($e[0].Open());try{$d=$r.ReadToEnd()|ConvertFrom-Json;if([string]$d.schema -eq $Script:PMMAIIOWorkOrderSchema){return $d}}finally{$r.Dispose()}}finally{$z.Dispose()};return $null
}
function Expand-PMMAIIOTrustedZip([string]$Zip,[string]$Dest){Add-Type -AssemblyName System.IO.Compression.FileSystem;New-Item -ItemType Directory -Force -Path $Dest|Out-Null;$root=[IO.Path]::GetFullPath($Dest).TrimEnd('\','/')+[IO.Path]::DirectorySeparatorChar;$z=[IO.Compression.ZipFile]::OpenRead($Zip);try{foreach($e in $z.Entries){$n=([string]$e.FullName).Replace('\','/');if(-not(Test-PMMAIIOCaseZipEntry $n)){throw ('Unsafe ZIP path: '+$n)};if([string]::IsNullOrWhiteSpace([string]$e.Name)){continue};$target=[IO.Path]::GetFullPath((Join-Path $Dest $n.Replace('/',[IO.Path]::DirectorySeparatorChar)));if(-not$target.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw 'ZIP path escaped case import root.'};$parent=Split-Path -Parent $target;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};$in=$e.Open();$out=[IO.File]::Open($target,[IO.FileMode]::Create,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$in.CopyTo($out)}finally{$out.Dispose();$in.Dispose()}}}finally{$z.Dispose()}}

function Import-PMMAIIOWorkOrder([string]$Path,$Doc,[switch]$Trusted,[switch]$AutoProcess){
  $wo=[string]$Doc.workOrderId;if(-not$wo){$wo='wo-'+[guid]::NewGuid().ToString('N')};$requested=[string]$Doc.case.caseId;$c=$null;if(Test-PMMAIIOCaseId $requested){$c=Get-PMMAIIOCase $requested};if(-not$c){$hit=@(Get-PMMAIIOCases|Where-Object{[string]$_.WorkOrderId -eq $wo}|Select-Object -First 1);if($hit.Count){$c=$hit[0]}};if(-not$c){$c=New-PMMAIIOCase -Title ([string]$Doc.case.title) -Type ([string]$Doc.case.type) -Description ([string]$Doc.case.description) -Transport ([string]$Doc.case.transport) -WorkOrderId $wo -NoInitialStep}
  $root=Get-PMMAIIOCasePath ([string]$c.CaseId);$inbox=Join-Path $root 'inbox';$copy=Join-Path $inbox ([IO.Path]::GetFileName($Path));Copy-Item -LiteralPath $Path -Destination $copy -Force;$import=Join-Path $root ('imports\'+[DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss'));if([IO.Path]::GetExtension($Path) -ieq '.zip'){Expand-PMMAIIOTrustedZip $Path $import}else{New-Item -ItemType Directory -Force -Path $import|Out-Null;Copy-Item $Path (Join-Path $import 'workorder.json') -Force}
  $c=Get-PMMAIIOCase ([string]$c.CaseId);$c.TrustedInbound=[bool]$Trusted;$c.LatestInbound=$copy;$actions=@();foreach($a in @($Doc.actions)){if(-not$a){continue};$name=[string]$a.action;if(-not$name){$name=[string]$a.capability};if(-not$name){continue};$actions+=,[pscustomobject]@{Id=[guid]::NewGuid().ToString('N');Action=$name.ToLowerInvariant();Status='Pending';Original=$a;ImportRoot=$import}};$c.PendingActions=$actions;$c.NextAction=$(if($actions.Count -gt 0){'PROCESS_REQUESTS'}else{'CREATE_HANDOFF'});Save-PMMAIIOCase $c|Out-Null;Add-PMMAIIOCaseStep $c 'WORK_ORDER_RECEIVED' ('Received AI work order: '+[IO.Path]::GetFileName($Path)) ([string]$c.NextAction) @($copy) ([pscustomobject]@{WorkOrderId=$wo;ActionCount=$actions.Count})|Out-Null
  if($AutoProcess -and $actions.Count -gt 0){Invoke-PMMAIIOCasePendingActions ([string]$c.CaseId)|Out-Null};return (Get-PMMAIIOCase ([string]$c.CaseId))
}

function Ensure-PMMAIIOCaseGameReference([string]$Id){$state=Get-PMMGameReferenceState;if([string]$state.Status -eq 'Current'){return};Set-PMMAIIOCaseProgress $Id 0 100 'Building Game Reference...' -Indeterminate;Build-PMMGameReferenceLibrary|Out-Null;$state=Get-PMMGameReferenceState;if([string]$state.Status -ne 'Current'){throw ('Game Reference build failed: '+[string]$state.Reason)}}
function Copy-PMMAIIOCaseVanillaFamily([string]$Id,[string]$Logical,[string]$Dest){Ensure-PMMAIIOCaseGameReference $Id;if(Get-Command Ensure-PMMAIIOGameReferenceFamilyExact -ErrorAction SilentlyContinue){Ensure-PMMAIIOGameReferenceFamilyExact -LogicalPath $Logical|Out-Null};$n=$Logical.Replace('\','/');$stem=$n.Substring(0,$n.Length-7);$root=Get-PMMGameReferenceCookedRoot;$files=[Collections.Generic.List[string]]::new();foreach($ext in @('.uasset','.uexp','.ubulk','.uptnl')){$rel=$stem+$ext;$src=Join-Path $root $rel.Replace('/',[IO.Path]::DirectorySeparatorChar);if(Test-Path -LiteralPath $src -PathType Leaf){$dst=Join-Path $Dest $rel.Replace('/',[IO.Path]::DirectorySeparatorChar);New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dst)|Out-Null;Copy-Item $src $dst -Force;$files.Add($dst)}};if($files.Count -eq 0){throw ('Vanilla family unavailable: '+$Logical)};return @($files.ToArray())}
function Resolve-PMMAIIOActionPak($Raw,[string]$ImportRoot){$p=[string]$Raw.packagePath;if($p -and $ImportRoot){$candidate=[IO.Path]::GetFullPath((Join-Path $ImportRoot $p));if(Test-Path -LiteralPath $candidate -PathType Leaf){return $candidate}};$p=[string]$Raw.path;if($p -and (Test-Path -LiteralPath $p -PathType Leaf)){return [IO.Path]::GetFullPath($p)};$name=[string]$Raw.name;if(-not$name){$name=[string]$Raw.providerName};foreach($m in @(Get-LibraryMods)){foreach($prop in @('Name','FileName','DisplayName')){if($m.PSObject.Properties.Name -contains $prop -and [string]$m.$prop -ieq $name){foreach($pp in @('Path','FullName','SourcePath','PakPath')){if($m.PSObject.Properties.Name -contains $pp -and (Test-Path -LiteralPath ([string]$m.$pp) -PathType Leaf)){return [string]$m.$pp}}}}};throw ('Could not resolve mod: '+$name)}
function Invoke-PMMAIIOTrustedProcess([string]$Id,$Raw,[string]$ImportRoot,[string]$Evidence,[switch]$Command){$c=Get-PMMAIIOCase $Id;if(-not$c.TrustedInbound){throw 'Program/command execution requires an explicitly trusted inbound file.'};$timeout=300;try{if($Raw.timeoutSeconds){$timeout=[Math]::Min(3600,[Math]::Max(1,[int]$Raw.timeoutSeconds))}}catch{};$working=[string]$Raw.workingDirectory;if(-not$working){$working=Get-PMMPath 'App'};$psi=[Diagnostics.ProcessStartInfo]::new();$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true
  if($Command){$cmd=[string]$Raw.command;if(-not$cmd){$cmd=[string]$Raw.commandLine};if(-not$cmd){throw 'run_command requires command text.'};$psi.FileName=$(if($env:ComSpec){$env:ComSpec}else{'cmd.exe'});$psi.Arguments='/d /s /c "'+$cmd+'"'}else{$p=[string]$Raw.packagePath;if($p){$p=[IO.Path]::GetFullPath((Join-Path $ImportRoot $p))}else{$p=[string]$Raw.path;if(-not$p){$p=[string]$Raw.program}};if(-not(Test-Path -LiteralPath $p -PathType Leaf)){try{$p=(Get-Command $p -ErrorAction Stop).Source}catch{}};if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw ('Program not found: '+$p)};$args=@($Raw.arguments|ForEach-Object{[string]$_});$ext=[IO.Path]::GetExtension($p).ToLowerInvariant();if($ext -in @('.cmd','.bat')){$psi.FileName=$(if($env:ComSpec){$env:ComSpec}else{'cmd.exe'});$psi.Arguments='/d /c "'+$p+'" '+($args -join ' ')}elseif($ext -eq '.ps1'){$psi.FileName='powershell.exe';$psi.Arguments='-NoProfile -ExecutionPolicy Bypass -File "'+$p+'" '+($args -join ' ')}else{$psi.FileName=$p;$psi.Arguments=($args -join ' ')}}
  $psi.WorkingDirectory=$working;New-Item -ItemType Directory -Force -Path $Evidence|Out-Null;$proc=[Diagnostics.Process]::new();$proc.StartInfo=$psi;[void]$proc.Start();$ot=$proc.StandardOutput.ReadToEndAsync();$et=$proc.StandardError.ReadToEndAsync();if(-not$proc.WaitForExit($timeout*1000)){try{$proc.Kill()}catch{};throw 'Requested process timed out.'};$proc.WaitForExit();$ot.Result|Set-Content (Join-Path $Evidence 'stdout.txt') -Encoding UTF8;$et.Result|Set-Content (Join-Path $Evidence 'stderr.txt') -Encoding UTF8;Write-PMMAIIOCaseJson (Join-Path $Evidence 'execution.json') ([ordered]@{Program=$psi.FileName;Arguments=$psi.Arguments;WorkingDirectory=$working;ExitCode=$proc.ExitCode;Utc=[DateTime]::UtcNow.ToString('o')}) 12;return [pscustomobject]@{Summary=('Process exited '+$proc.ExitCode);Artifacts=@((Join-Path $Evidence 'stdout.txt'),(Join-Path $Evidence 'stderr.txt'),(Join-Path $Evidence 'execution.json'))}}

function Invoke-PMMAIIOCaseAction([string]$Id,$Action){$raw=$Action.Original;$root=Join-Path (Get-PMMAIIOCaseEvidencePath $Id) ([string]$Action.Id);New-Item -ItemType Directory -Force -Path $root|Out-Null;$name=[string]$Action.Action;switch($name){
  'ensure_game_reference'{Ensure-PMMAIIOCaseGameReference $Id;return [pscustomobject]@{Summary='Game Reference is current';Artifacts=@()}}
  'extract_game_reference_asset'{$name='include_game_reference_family'}
  'include_vanilla_family'{$name='include_game_reference_family'}
  'include_game_reference_family'{$logical=[string]$raw.logicalPath;if(-not$logical){$logical=[string]$raw.path};$files=Copy-PMMAIIOCaseVanillaFamily $Id $logical (Join-Path $root 'vanilla');return [pscustomobject]@{Summary=('Collected Vanilla family '+$logical);Artifacts=@($files)}}
  'query_game_reference'{Ensure-PMMAIIOCaseGameReference $Id;$q=[string]$raw.query;if(-not$q){$q=[string]$raw.logicalPath};$hits=@(Search-PMMAIIOGameReferenceFamilies -Query $q -MaximumResults 100);$p=Join-Path $root 'query.json';Write-PMMAIIOCaseJson $p ([ordered]@{Query=$q;Results=$hits}) 40;return [pscustomobject]@{Summary=('Queried Game Reference for '+$q);Artifacts=@($p)}}
  'read_pmm_log'{$name='include_log'}
  'include_log'{$logs=Get-PMMPath 'Logs';$p=Join-Path $logs 'PalModMerger.log';if(-not(Test-Path $p)){$first=@(Get-ChildItem $logs -File|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1);if($first.Count){$p=$first[0].FullName}else{$p=''}};if(-not$p){throw 'PMM log not found.'};$d=Join-Path $root 'PalModMerger.log';Get-Content $p -Tail 2000|Set-Content $d -Encoding UTF8;return [pscustomobject]@{Summary='Collected PMM log';Artifacts=@($d)}}
  'include_full_pak'{$name='include_mod_full'}
  'include_mod_full'{$pak=Resolve-PMMAIIOActionPak $raw ([string]$Action.ImportRoot);$d=Join-Path $root ([IO.Path]::GetFileName($pak));Copy-Item $pak $d -Force;return [pscustomobject]@{Summary=('Collected '+[IO.Path]::GetFileName($pak));Artifacts=@($d)}}
  'extract_provider_asset'{$name='include_mod_family'}
  'include_mod_family'{$pak=Resolve-PMMAIIOActionPak $raw ([string]$Action.ImportRoot);$logical=[string]$raw.logicalPath;$d=Join-Path $root 'family';Export-PakAssetFamilyExact $pak $logical $d|Out-Null;$files=@(Get-ChildItem $d -File -Recurse|ForEach-Object{$_.FullName});return [pscustomobject]@{Summary=('Collected mod family '+$logical);Artifacts=$files}}
  'include_file'{$c=Get-PMMAIIOCase $Id;if(-not$c.TrustedInbound){throw 'External file read requires trusted inbound.'};$p=[string]$raw.path;if(-not(Test-Path $p -PathType Leaf)){throw 'Requested file not found.'};$d=Join-Path $root ([IO.Path]::GetFileName($p));Copy-Item $p $d -Force;return [pscustomobject]@{Summary=('Collected file '+[IO.Path]::GetFileName($p));Artifacts=@($d)}}
  'run_program'{return (Invoke-PMMAIIOTrustedProcess $Id $raw ([string]$Action.ImportRoot) $root)}
  'run_command'{return (Invoke-PMMAIIOTrustedProcess $Id $raw ([string]$Action.ImportRoot) $root -Command)}
  default{throw ('Unsupported work-order action: '+$name)}
}}
function Invoke-PMMAIIOCasePendingActions([string]$Id){Reset-PMMAIIOCaseAutomation;$c=Get-PMMAIIOCase $Id;$pending=@($c.PendingActions|Where-Object{[string]$_.Status -eq 'Pending'});$done=0;$summ=[Collections.Generic.List[string]]::new();$arts=[Collections.Generic.List[string]]::new();foreach($a in $pending){if($Script:PMMAIIOCaseCancelRequested){break};$done++;Set-PMMAIIOCaseProgress $Id ($done-1) ([Math]::Max(1,$pending.Count)) ('Processing '+$a.Action+'...');try{$r=Invoke-PMMAIIOCaseAction $Id $a;$a.Status='Complete';$summ.Add([string]$r.Summary);foreach($p in @($r.Artifacts)){$arts.Add([string]$p)};$c.PendingActions=@($c.PendingActions);Save-PMMAIIOCase $c|Out-Null}catch{$a.Status='Failed';$a|Add-Member -NotePropertyName Error -NotePropertyValue $_.Exception.Message -Force;$c.PendingActions=@($c.PendingActions);$c.FailedActions=@($c.FailedActions)+@($a);Save-PMMAIIOCase $c|Out-Null;Set-PMMAIIOCaseProgress $Id $done ([Math]::Max(1,$pending.Count)) ('Failed: '+$_.Exception.Message) -Completed;throw}}
  $c=Get-PMMAIIOCase $Id;$c.CompletedActions=@($c.CompletedActions)+@($c.PendingActions|Where-Object{[string]$_.Status -eq 'Complete'});$c.NextAction='CREATE_HANDOFF';$c.Status='READY_FOR_HANDOFF';Save-PMMAIIOCase $c|Out-Null;Set-PMMAIIOCaseProgress $Id $pending.Count ([Math]::Max(1,$pending.Count)) 'Requested work complete. Create handoff for AI.' -Completed;Add-PMMAIIOCaseStep $c 'REQUESTS_PROCESSED' $(if($summ.Count){$summ -join '; '}else{'Requested work complete'}) 'CREATE_HANDOFF' @($arts.ToArray()) ([pscustomobject]@{Completed=$done})|Out-Null;return (Get-PMMAIIOCase $Id)}

function New-PMMAIIOCaseHandoff([string]$Id,[int]$FromStep=0){$c=Get-PMMAIIOCase $Id;if(-not$c){throw 'Case not found.'};if($FromStep -le 0){$FromStep=[int]$c.SelectedStep;if($FromStep -le 0){$FromStep=[int]$c.CurrentStep}};$step=Get-PMMAIIOCaseStep $Id $FromStep;if(-not$step){throw 'Selected step not found.'};$stage=Join-Path (Join-PMMPath 'Temp' 'AIIOCaseHandoff') ([guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $stage|Out-Null;try{Write-PMMAIIOCaseJson (Join-Path $stage 'case.json') ([ordered]@{Schema='PMM_AIIO_CASE_HANDOFF_V3';CaseId=$Id;FromStep=$FromStep;State=$step.State;GeneratedUtc=[DateTime]::UtcNow.ToString('o')}) 80;$sd=Join-Path $stage 'steps';New-Item -ItemType Directory -Force -Path $sd|Out-Null;$artifactSet=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);for($n=1;$n -le $FromStep;$n++){$s=Get-PMMAIIOCaseStep $Id $n;if($s){Write-PMMAIIOCaseJson (Join-Path $sd ('step-{0:D4}.json' -f $n)) $s 90;foreach($p in @($s.Artifacts)){if($p -and (Test-Path -LiteralPath ([string]$p) -PathType Leaf)){[void]$artifactSet.Add([string]$p)}}}};$ed=Join-Path $stage 'evidence';New-Item -ItemType Directory -Force -Path $ed|Out-Null;$i=0;foreach($p in $artifactSet){$i++;Copy-Item $p (Join-Path $ed (('{0:D3}_' -f $i)+[IO.Path]::GetFileName($p))) -Force};Write-PMMAIIOCaseJson (Join-Path $stage 'capabilities.json') ([ordered]@{Schema='PMM_AIIO_CASE_CAPABILITIES_V3';WorkOrderSchema=$Script:PMMAIIOWorkOrderSchema;Actions=@('ensure_game_reference','include_game_reference_family','query_game_reference','include_log','include_mod_full','include_mod_family','include_file','run_program','run_command');Transports=@('AUTO','MANUAL_ZIP','AGENT_SERVER','GIT','NEXUS','LINK')}) 20;Add-Type -AssemblyName System.IO.Compression.FileSystem;$folder=Get-PMMAIIOCaseHandoffsPath $Id;$zip=Join-Path $folder ('PMM_AIIO_CASE_'+$Id+'_STEP_'+('{0:D2}' -f $FromStep)+'.zip');if(Test-Path $zip){Remove-Item $zip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($stage,$zip,[IO.Compression.CompressionLevel]::Optimal,$false);$c=Get-PMMAIIOCase $Id;$c.LatestHandoff=$zip;$c.NextAction='WAIT_FOR_AI';Save-PMMAIIOCase $c|Out-Null;Add-PMMAIIOCaseStep $c 'HANDOFF_CREATED' ('Created AI handoff from step '+$FromStep) 'WAIT_FOR_AI' @($zip) ([pscustomobject]@{FromStep=$FromStep})|Out-Null;return [pscustomobject]@{ZipPath=$zip;FromStep=$FromStep}}finally{Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue}}
