param([string]$Repository=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2
$testRoot=Join-Path ([IO.Path]::GetTempPath()) ('pmm-update-tx-'+[Guid]::NewGuid().ToString('N'));$Script:Root=Join-Path $Repository 'PMM';$Script:FailAfterDeployment=$false
$stateRoot=Join-Path $testRoot 'Workspace\State';$updateRoot=Join-Path $testRoot 'Workspace\ModUpdates';$libraryDir=Join-Path $testRoot 'Workspace\Mods\001-Example';$gameRoot=Join-Path $testRoot 'GameMods'
foreach($d in @($stateRoot,$updateRoot,$libraryDir,$gameRoot)){[void][IO.Directory]::CreateDirectory($d)}
function Assert-True($Value,[string]$Message){if(-not$Value){throw $Message}}
function Join-PMMPath([string]$Kind,[string]$Child){$base=switch($Kind){'State'{$stateRoot}'ModUpdates'{$updateRoot}'Cache'{Join-Path $testRoot 'Workspace\Cache'}default{Join-Path $testRoot ('Workspace\'+$Kind)}};if($Child){Join-Path $base $Child}else{$base}}
function Get-Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Write-PMMJsonAtomic([string]$Path,$Value,[int]$Depth=40,[string]$Schema=''){if($Script:FailAfterDeployment -and $Path -like '*\transaction.json' -and ($Value.PSObject.Properties.Name -contains 'DeploymentTransactionBackup') -and $Value.DeploymentTransactionBackup){$Script:FailAfterDeployment=$false;throw 'INJECTED_POST_DEPLOY_FAILURE'};[void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path));$tmp=$Path+'.tmp';[IO.File]::WriteAllText($tmp,($Value|ConvertTo-Json -Depth $Depth),[Text.UTF8Encoding]::new($false));if(Test-Path $Path){Remove-Item $Path -Force};[IO.File]::Move($tmp,$Path)}
function Read-PMMJsonFile([string]$Path,[string]$Schema=''){if(-not(Test-Path $Path)){throw 'missing'};$v=Get-Content $Path -Raw|ConvertFrom-Json;if($Schema -and $v.Schema -ne $Schema){throw 'schema'};$v}
function Get-PMMAnalysisValue($Object,[string]$Name,$Default=$null){if($null -ne $Object -and $Object.PSObject.Properties.Name -contains $Name){return $Object.$Name};$Default}
function Get-PMMAnalysisHash($Value){$json=$Value|ConvertTo-Json -Depth 30 -Compress;$sha=[Security.Cryptography.SHA256]::Create();try{(($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($json))|ForEach-Object{$_.ToString('x2')}) -join '')}finally{$sha.Dispose()}}
function Get-PMMUpdateFingerprint {'fixture-fingerprint'}
function Test-PMMPalworldRunning {$false}
function Get-GameModsPath {$gameRoot}
function Get-PMMDeploymentStatePath {Join-Path $stateRoot 'deployment-state.json'}
function Read-PMMDeploymentState {if(Test-Path (Get-PMMDeploymentStatePath)){Read-PMMJsonFile (Get-PMMDeploymentStatePath)}else{$null}}
function Write-PMMDeploymentState($State){Write-PMMJsonAtomic (Get-PMMDeploymentStatePath) $State -Depth 20}
function Get-PMMPendingRemovalRecords {@()}
function Invoke-PMMDeploymentTransaction($Context,$Operations,$State){foreach($action in @($Operations.CopyActions)){Copy-Item $action.Source $action.Destination -Force;if((Get-Sha256 $action.Destination) -ne $action.ExpectedHash){throw 'fixture deployment hash mismatch'}};Write-PMMDeploymentState $State;$backup=Join-Path $testRoot 'DeploymentBackup';[void][IO.Directory]::CreateDirectory($backup);$backup}
function Get-PMMLibrarySignature([array]$Mods){'sig-'+(@($Mods|ForEach-Object{$_.Hash}) -join '-')}
function Clear-PMMLibraryHashCache {}
function Clear-PakEntryCache {}
function Clear-PMMAnalysisState {}
function Get-PMMModOrigin($Mod){[pscustomobject]@{Schema='PMM_MOD_ORIGIN_V2';LocalSha256=$Mod.Hash;Name=$Mod.Name;Provider='Nexus';Game='palworld';ModId='10';FileId='100';Version='1';AssetName='main.zip';Variant='Main';IdentityStatus='UserLinked';ArchivePath='';ArchiveSha256='';UpdatedUtc=[DateTime]::UtcNow.ToString('o')}}
function Find-PMMLibraryMod([string]$Name){$path=Join-Path $libraryDir $Name;if(Test-Path $path){[pscustomobject]@{Name=$Name;Path=$path;Hash=(Get-Sha256 $path);Enabled=$true;Priority=7;Size=(Get-Item $path).Length}}}
function Get-LibraryMods {$m=Find-PMMLibraryMod 'Example_P.pak';if($m){$m}}
function Get-PMMDisabledMods {@()}
. (Join-Path $Script:Root 'Modules\Analysis\Updates.Service.ps1')
. (Join-Path $Script:Root 'Modules\Analysis\Updates.Transaction.ps1')
try{
  $oldPath=Join-Path $libraryDir 'Example_P.pak';$newPath=Join-Path $testRoot 'Example-new.pak';[IO.File]::WriteAllBytes($oldPath,[byte[]](1,2,3,4));[IO.File]::WriteAllBytes($newPath,[byte[]](9,8,7,6));$oldHash=Get-Sha256 $oldPath;$newHash=Get-Sha256 $newPath;Copy-Item $oldPath (Join-Path $gameRoot 'Example_P.pak')
  $state=[pscustomobject]@{SchemaVersion=3;Deployed=[DateTime]::UtcNow.ToString('o');SourceSignature='old';SourceMods=@([pscustomobject]@{Name='Example_P.pak';Hash=$oldHash;Deployed=$true});SuppressedAlternatives=@();Patch=$null};Write-PMMDeploymentState $state
  $candidate=[pscustomobject]@{Schema='PMM_MOD_UPDATE_CANDIDATE_V2';PlanId='fixture-plan';LibraryFingerprint=(Get-PMMUpdateFingerprint);LibraryRows=@(Get-PMMUpdateLibraryRows);AutomaticEligible=$true;Blockers=@();PakPath=$newPath;PakSha256=$newHash;ArchivePath=$newPath;ArchiveSha256=$newHash;OriginalSha256=$oldHash;Applied=$false;Update=[pscustomobject]@{Mod='Example_P.pak';Origin=(Get-PMMModOrigin (Find-PMMLibraryMod 'Example_P.pak'));Candidate=[pscustomobject]@{FileId='101';Version='2';AssetName='main-v2.zip'}}}
  $Script:FailAfterDeployment=$true;$failed=$false;$failure='';try{[void](Invoke-PMMUpdateApply $candidate -Auto)}catch{$failure=$_.Exception.Message;$failed=($failure -like '*INJECTED_POST_DEPLOY_FAILURE*')};$Script:FailAfterDeployment=$false
  Assert-True $failed ('Injected commit failure did not reach the rollback path. Actual: '+$failure);Assert-True ((Get-Sha256 $oldPath) -eq $oldHash) 'Library rollback did not restore the previous PAK.';Assert-True ((Get-Sha256 (Join-Path $gameRoot 'Example_P.pak')) -eq $oldHash) 'Game rollback did not restore the previous PAK.';Assert-True ((Read-PMMDeploymentState).SourceMods[0].Hash -eq $oldHash) 'Deployment state rollback did not restore the previous hash.';Assert-True (-not(Test-Path (Get-PMMModOriginPath $newHash))) 'Rollback left the new origin metadata active.'
  $rolled=@(Get-ChildItem (Join-Path $updateRoot 'Archive') -Directory|ForEach-Object{Read-PMMJsonFile (Join-Path $_.FullName 'transaction.json') -Schema PMM_MOD_UPDATE_TRANSACTION_V1}|Where-Object{$_.State -eq 'RolledBack'});Assert-True ($rolled.Count -eq 1) 'Failed update transaction was not recorded as rolled back.'
  $recoveryId='20260921_010203_deadbeef';$recoveryRoot=Join-Path (Join-Path $updateRoot 'Archive') $recoveryId;$libraryBackup=Join-Path $recoveryRoot 'LibraryBefore';[void][IO.Directory]::CreateDirectory($recoveryRoot);Copy-Item $libraryDir $libraryBackup -Recurse;Copy-Item $oldPath (Join-Path $recoveryRoot 'GameBefore.pak');Copy-Item (Get-PMMDeploymentStatePath) (Join-Path $recoveryRoot 'deployment-state.before.json');Copy-Item $newPath $oldPath -Force;Copy-Item $newPath (Join-Path $gameRoot 'Example_P.pak') -Force;$newState=Read-PMMDeploymentState;$newState.SourceMods[0].Hash=$newHash;Write-PMMDeploymentState $newState
  $orphanOrigin=Get-PMMModOriginPath $newHash;Write-PMMJsonAtomic $orphanOrigin ([ordered]@{Schema='PMM_MOD_ORIGIN_V2';LocalSha256=$newHash}) -Schema PMM_MOD_ORIGIN_V2
  $incomplete=[pscustomobject]@{Schema='PMM_MOD_UPDATE_TRANSACTION_V1';Id=$recoveryId;State='LibraryCommitted';UpdatedUtc='';Error='';OriginNewPath=$orphanOrigin;OriginNewBackup='';GamePath=(Join-Path $gameRoot 'Example_P.pak');GameBackup=(Join-Path $recoveryRoot 'GameBefore.pak');GameExisted=$true;DeploymentStateBackup=(Join-Path $recoveryRoot 'deployment-state.before.json');LibraryPath=$libraryDir;LibraryBackup=$libraryBackup};Write-PMMJsonAtomic (Join-Path $recoveryRoot 'transaction.json') $incomplete -Depth 30
  Repair-PMMIncompleteUpdateTransactions;Assert-True ((Get-Sha256 $oldPath) -eq $oldHash) 'Restart recovery did not restore the library.';Assert-True ((Get-Sha256 (Join-Path $gameRoot 'Example_P.pak')) -eq $oldHash) 'Restart recovery did not restore ~mods.';Assert-True ((Read-PMMDeploymentState).SourceMods[0].Hash -eq $oldHash) 'Restart recovery did not restore deployment state.';Assert-True ((Read-PMMJsonFile (Join-Path $recoveryRoot 'transaction.json')).State -eq 'RolledBack') 'Restart recovery did not finish the transaction.';Assert-True (-not(Test-Path $orphanOrigin)) 'Restart recovery left the uncommitted origin metadata active.'
  $plan=[pscustomobject]@{Schema='PMM_UPDATE_PLAN_V1';Id='fixture-plan';CreatedUtc='';LibraryFingerprint=(Get-PMMUpdateFingerprint);Results=@([pscustomobject]@{LocalSha256=$oldHash;Status='UPDATE_AVAILABLE';Message='fixture';CompatibilityProven=$false})};Write-PMMJsonAtomic (Get-PMMUpdatePlanPath) $plan -Depth 20 -Schema PMM_UPDATE_PLAN_V1
  $candidate.LibraryFingerprint=Get-PMMUpdateFingerprint;$candidate.LibraryRows=@(Get-PMMUpdateLibraryRows);$candidate.Applied=$false
  $committed=Invoke-PMMUpdateApply $candidate;Update-PMMUpdatePlanAfterApply $candidate $committed;$advanced=Read-PMMUpdatePlan;Assert-True (Test-Path (Get-PMMModOriginPath $newHash)) 'Committed update did not persist new origin metadata.'
  Assert-True $advanced.IsCurrent 'The saved plan was not safely advanced after a committed update.';Assert-True ($advanced.Results[0].Status -eq 'APPLIED') 'The applied row was not retired from the update batch.'
  $candidatePath=Join-Path (Join-Path (Get-PMMUpdateRoot) 'Candidates') 'fixture/candidate.json';[void][IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($candidatePath));Write-PMMJsonAtomic $candidatePath $candidate -Depth 20
  Set-PMMPendingUpdateApply 'fixture-plan' @([pscustomobject]@{LocalSha256=$newHash;CandidatePath=$candidatePath}) $true;$pending=Get-PMMPendingUpdateApply
  Assert-True ($pending.Items.Count -eq 1 -and $pending.Items[0].LocalSha256 -eq $newHash) 'Deferred update state did not roundtrip.';Clear-PMMPendingUpdateApply;Assert-True (-not(Get-PMMPendingUpdateApply)) 'Deferred update state was not cleared.'
  'Mod update transaction regression: PASS'
}finally{if(Test-Path $testRoot){Remove-Item $testRoot -Recurse -Force}}