<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><UseAppHost>false</UseAppHost><AssemblyName>PMM.AssetTools</AssemblyName></PropertyGroup><ItemGroup><Reference Include="UAssetAPI"><HintPath>../../../PMM/Engine/AssetReader/UAssetAPI.dll</HintPath></Reference><Reference Include="Newtonsoft.Json"><HintPath>../../../PMM/Engine/AssetReader/Newtonsoft.Json.dll</HintPath></Reference><Reference Include="ZstdSharp"><HintPath>../../../PMM/Engine/AssetReader/ZstdSharp.dll</HintPath></Reference></ItemGroup></Project>